NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
WEB_AUTH_ENDPOINT="http://localhost:8001/auth"
KYC_SERVER="http://localhost:8001/kyc"
TRANSFER_SERVER_SEP0024="http://localhost:8001/sep24"
ACCOUNTS=["GDEMOANCHORISSUER123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"]
CURRENCIES=[{ code="USDTEST", issuer="GDEMOANCHORISSUER123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ" }]